In [1]:
import numpy as np 

How to extract items that satisfy a given condition from 1D array?

In [276]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

 How to replace items that satisfy a condition with another value in numpy array?

In [277]:
arr[arr % 2 == 1] = 55
arr

array([ 0, 55,  2, 55,  4, 55,  6, 55,  8, 55])

How to replace items that satisfy a condition without affecting the original array?

In [279]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out
#> [0 1 2 3 4 5 6 7 8 9]


[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Convert a 1D array to a 2D array with 2 rows

In [280]:
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

How to get the positions where elements of two arrays match?

In [281]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

 How to extract all numbers between a given range from a numpy array?


In [282]:
a = np.arange(15)
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

How to reverse the rows of a 2D array?

In [295]:
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

How to reverse the columns of a 2D array

In [ ]:
arr = np.arange(9).reshape(3,3)
arr[:, ::-1]

How to filter a numpy array based on two or more conditions?

In [306]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Solution
condition = (iris_2d[:, 0] > 1) & (iris_2d[:, 3] < 8.0)
iris_2d[condition]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       ...,
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [ ]:
How to drop rows that contain a missing value from a numpy array?
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]

In [ ]:
How to find the correlation between two columns of a numpy array?
np.corrcoef(iris[:, 0], iris[:, 2])[0, 1]

 How to find if a given array has any null values?

In [ ]:
np.isnan(iris_2d).any()

How to replace all missing values with 0 in a numpy array?

In [ ]:
iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:4]

How to find the count of unique values in a numpy array?

In [ ]:
species = np.array([row.tolist()[4] for row in iris])
np.unique(species, return_counts=True)

. How to convert a numeric to a categorical (text) array?

In [ ]:
# Bin petallength 
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])

# Map it to respective category
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

# View
petal_length_cat[:4]

In [ ]:
How to create a new column from existing columns of a numpy array?
How to get the second largest value of an array when grouped by another array?

How to sort a 2D array by a column

In [ ]:
print(iris[iris[:,0].argsort()][:20])

How to replace all values greater than a given value to a given cutoff?

In [ ]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
Show Solution
# Input
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# Solution 1: Using np.clip
np.clip(a, a_min=10, a_max=30)

 to Reverse  array

In [3]:
ar1 = np.arange(50)
ar1 = ar1[::-1]
ar1

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

 Create a 3x3 matrix with values ranging from 0 to 

In [9]:
ar2 = np.arange(9).reshape(3,3)
ar2


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3x3x3 array with random values

In [10]:
ar3 = np.random.random((3,3,3))
ar3

array([[[0.9467381 , 0.51118865, 0.98654138],
        [0.94295472, 0.23862925, 0.88341447],
        [0.73411918, 0.78988594, 0.54908585]],

       [[0.5619031 , 0.99756665, 0.03225589],
        [0.52397491, 0.27110882, 0.87430761],
        [0.86469595, 0.46581396, 0.08577647]],

       [[0.16282267, 0.32923265, 0.37249457],
        [0.65974628, 0.71578379, 0.54477029],
        [0.05005175, 0.35284725, 0.35868202]]])

 Create a 3x3 array with intger values and find the minimum and maximum values 

In [37]:
ar4 = np.random.randint(100,size=(3,3))
arMaX ,arMIN ,arMEAN  = ar4.max() , ar4.min(),ar4.mean()
print(arMaX,arMIN,arMEAN)

94 5 55.666666666666664


 Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [49]:
ar5 = np.diag(1+np.arange(4))
ar5

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [59]:
ar6 = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.unravel_index(1000,(6,9,20)))

(5, 5, 0)


 Normalize a 5x5 random matrix

 Normalize a 5x5 random or int matrix

In [88]:
ar7 = np.random.random((5,5))
ar7 = (ar7 - np.mean (ar7)) / (np.std (ar7))
print(ar7)

[[-0.26383836  0.44077811 -1.20752389 -0.6554677   1.43704867]
 [ 0.74109492 -1.8765156  -1.73383988  0.4797526   0.8334334 ]
 [-0.38584422 -1.87061053  1.58571135 -0.10646313 -0.07284303]
 [ 1.25211296 -0.15950149  0.40440733 -0.95223449 -0.13255188]
 [ 0.38175876 -0.07555129  1.67088994 -0.55369333  0.81949075]]


Given a 1D array, negate all elements which are between 3 and 8, in place

In [98]:
ar8 = np.arange(11)
#ar8[(ar8)]*=-1 all the elements as negative
ar8[(ar8>= 5)]*=-1
ar8

array([  0,   1,   2,   3,   4,  -5,  -6,  -7,  -8,  -9, -10])

. How to find common values between two arrays?

In [99]:
ar9  = np.array([1,2,3,4,5,6,7,8,9,10])
ar10 = np.array([1,0,5,11,22,55,66,10])
print(np.intersect1d(ar9,ar10))

[ 1  5 10]


In [133]:
ar9  = np.random.randint(0,10,10)
ar10 = np.random.randint(0,10,10)
print(np.intersect1d(ar9,ar10))

[0 1 7]


How to get the dates of yesterday, today and tomorrow?

In [134]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

 How to get all the dates corresponding to the month of July 2016?

In [ ]:
Z = np.arange('2021-07', '2022-08', dtype='datetime64[D]')
print(Z)

Consider a generator function that generates 10 integers and use it to build an array

In [164]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=int,count=-1)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


Create a random vector of size 10 and sort it

In [188]:
ar11 = np.random.random(10)
ar11.sort()
print(ar11)

[0.25651616 0.26391919 0.31016086 0.37724884 0.43115656 0.55368884
 0.58008441 0.74192477 0.91758    0.96162215]


How to sum a small array faster than np.sum

In [189]:
#arr12 = np.arange(5)
ar12 = np.array([1,2,3,4,5])

np.add.reduce(ar12)

15

Consider two random array A and B, check if they are equal

In [191]:
eq_ar = np.allclose(ar9,ar10)
eq_ar

False

In [192]:
#لتحقق من كل من قيم الشكل والعنصر ، لا تسامح (يجب أن تكون القيم متساوية تمامًا
equal = np.array_equal(ar9,ar10)
equal

False

create random vector of size 10 and replace the maximum value by

In [196]:
ar13 = np.random.random(10)
ar13[ar13.argmax()] = 0
print(ar13)

[0.13901447 0.02139559 0.6445592  0.30950849 0.74862748 0.
 0.55078976 0.77971033 0.50160202 0.20302078]


How to find the closest value (to a given scalar) in a vector

In [208]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

9


How to convert a float (32 bits) array into an integer (32 bits) in place

In [209]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


 What is the equivalent of enumerate for numpy arrays?

In [215]:
Z = np.arange(4).reshape(2,2)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


Subtract the mean of each row of a matrix

In [222]:

X = np.random.rand(5, 2)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)


[[ 0.14282905 -0.14282905]
 [ 0.01215471 -0.01215471]
 [ 0.12310647 -0.12310647]
 [-0.2313569   0.2313569 ]
 [-0.02943617  0.02943617]]


How to find the most frequent value in an array

In [ ]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

In [241]:
ar14 = np.array([10,5,4,20,4,9,105,36,6,8,12])

In [246]:
Z =ar14
np.random.shuffle(Z)
n = 3

In [249]:
print(Z[np.argsort(Z)[-n:]])



[ 20  36 105]
