In [1]:
import numpy as np

In [2]:
d1=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [26]:
d1.shape

(2, 5)

In [3]:
row,col = d1.shape
print("the number of rows is:",row)
print("the number of column is:",col)

the number of rows is: 2
the number of column is: 5


#### لتحديد نطاق معين من الارقام وتحديد حجم المصفوفة مع امكانية تغير نوع القيم العشوائية المراد اختيارها

In [4]:
d2 = np.random.randint(1,10,dtype=int,size = (2,5))
d2
#d2 = np.random.randint(starting point,stoping point,size = (number of rows,number of colums))

array([[9, 3, 9, 3, 3],
       [3, 7, 6, 9, 7]])

In [169]:
arr36 = np.random.rand(10,2)
arr36

#has no dtype

array([[0.92034131, 0.64780823],
       [0.16480295, 0.70225668],
       [0.58463965, 0.13560134],
       [0.31012369, 0.08286495],
       [0.70343787, 0.42595322],
       [0.12719466, 0.8828609 ],
       [0.59806217, 0.52534462],
       [0.25718056, 0.32666537],
       [0.1132852 , 0.91276171],
       [0.7419444 , 0.91692752]])

In [6]:
d1 =np.arange(1,12,5,dtype=int)
#d1 =np.arange(starting point,stopint point,steps,dtype=int)

#dtype=float
#dtype=complex
d1

array([ 1,  6, 11])

### لتحديد نوعية قيمة العناصر في المصفوفة

In [10]:
d4 = np.array([1,2,3,4,5,6],dtype=np.int64)
print(d4)
d4.shape

[1 2 3 4 5 6]


(6,)

## لتحويل لست الى مصفوفة والعكس بالعكس 

In [118]:
lis = [1,2,3,4]

print(type(lis))

<class 'list'>


In [119]:
lis

[1, 2, 3, 4]

In [127]:
n = np.array(lis)
n

array([1, 2, 3, 4])

In [316]:
y = np.asarray(lis)
y

array([1, 2, 3, 4])

In [128]:
m = list(n)
m

[1, 2, 3, 4]

In [129]:
s = set(n)
s

{1, 2, 3, 4}

In [318]:
t = tuple(n)
t

(False, True, True, True, False, True)

In [132]:
f = np.arange(1,15)

In [133]:
newlst = f.tolist()
print(newlst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


### لتحويل مصفوفة او اي نوع الى ماتركس

In [317]:
np.asmatrix(t)

matrix([[ 1,  2,  3,  7],
        [ 4,  5,  6, 10]])

In [138]:
arr13 = np.ones((4,5))
arr14 = np.zeros((4,5))

print(arr13)
print("----")
print(arr14)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
----
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
arr25 = np.arange(20).reshape(4,5)
print(arr25)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [14]:
#ضع لي المصفوفه رقم 25 في  مصفوفتين
arr28 = arr25.reshape(2,-1)
#arr28 = arr25.reshape(number of array , -1)

print(arr28)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [15]:
#هنا يمكنك التحكم في عدد العناصر الي تاخذه المصفوفة
arr29 = arr25.reshape(-1, 5)
#arr29 = arr25.reshape(-1, عند العناصر اللي تبغها في كل مصفوفة)

print(arr29)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### دمج مصفوفات حسب توافق الصفوفة او الاعمدة

In [16]:
ma =np.array([[1,2,3,7,11], [4,5,6,10,12]]) 
maa =np.array([[8,8,8,8], [9,9,9,9]])
#حسب الصفوف

In [17]:
c = np.concatenate((ma,maa),axis=1)
c
#c = np.concatenate((ma,maa)) اذ كانت المصفوفات بعد واحد مايحتاج axis


array([[ 1,  2,  3,  7, 11,  8,  8,  8,  8],
       [ 4,  5,  6, 10, 12,  9,  9,  9,  9]])

In [18]:
t =np.array([[1,2,3,7], [4,5,6,10]]) 
#على حسب الاعمدة

In [19]:
cc = np.concatenate((t,maa),axis=0)
cc

array([[ 1,  2,  3,  7],
       [ 4,  5,  6, 10],
       [ 8,  8,  8,  8],
       [ 9,  9,  9,  9]])

### دالة لانشاء مصفوفة وتحدد عدد الاعمدة والاسطر فيما بعد

In [51]:
def createMatrix(rows=10, cols=10):
    return np.random.randint(100, size=(rows, cols))
print(createMatrix())

[[49 89 33 12 46 32 96 87 76 20]
 [61 81 69  0 69 56 41 95 47 11]
 [32 97 50 77 44  0 55 97 14 95]
 [63 20 89 58 35 79 44 44 50 61]
 [20 35 75 41 50 32  7 36 41 95]
 [34 39 88 69 54 68 84  4 75 33]
 [95 86 44 22 40 16 13 56 93 19]
 [26 30 85 15 44 49 49 82 27 46]
 [65 50 17 90 67 71 63  9 26 11]
 [75 71 71 45 85 50 64 74 51 44]]


In [52]:
print(createMatrix(3,3))

[[15 90 44]
 [15 33 46]
 [83 43 18]]


In [23]:
def createMatrix_flaot(rows=0, cols=0):
    return np.random.rand(1,100)


In [27]:
createMatrix_flaot((1,5))

array([[0.84161566, 0.39489944, 0.33512859, 0.43755288, 0.37266122,
        0.55124134, 0.34400193, 0.22986375, 0.0906635 , 0.26171255,
        0.33374771, 0.86143647, 0.75967961, 0.54323122, 0.63477965,
        0.96515435, 0.17993979, 0.55625343, 0.02316818, 0.32694987,
        0.26653419, 0.85255023, 0.40555143, 0.75647447, 0.35152743,
        0.36572147, 0.05765883, 0.06396817, 0.63060716, 0.97634143,
        0.74136752, 0.06818545, 0.13544091, 0.31778508, 0.19849409,
        0.16367361, 0.71734481, 0.9644024 , 0.229609  , 0.02662126,
        0.82848954, 0.87910843, 0.96079523, 0.97183545, 0.67381015,
        0.22205499, 0.06872891, 0.96801439, 0.11510367, 0.07126646,
        0.04301679, 0.43057121, 0.14880835, 0.92870978, 0.2787367 ,
        0.61485484, 0.19609558, 0.00769033, 0.78762029, 0.09279982,
        0.03501515, 0.77170433, 0.73083115, 0.27453584, 0.66915627,
        0.37271204, 0.72737379, 0.52537762, 0.34099355, 0.56850989,
        0.35196148, 0.61397072, 0.99141262, 0.30

In [59]:
np.random.seed(0)
dd = np.random.randint(1,7,size=10)
dd

array([5, 6, 1, 4, 4, 4, 2, 4, 6, 3])

In [205]:
dq = np.unique(dd)
dq

array([1, 2, 3, 4, 5, 6])

In [208]:
x , index = np.unique(dd,return_index=True)
print(x,index)

[1 2 3 4 5 6] [2 6 9 3 0 1]


In [209]:
u , indexx = np.unique(dd,return_counts=True)
print(u,indexx)

[1 2 3 4 5 6] [1 1 1 4 1 2]


In [210]:
arr43 = np.arange(2,10).reshape(4,2)
print(arr43)

[[2 3]
 [4 5]
 [6 7]
 [8 9]]


In [211]:
print(np.max(arr43, axis=1))
#prints the max value in each row

[3 5 7 9]


In [213]:
print(np.max(arr43))

9


In [214]:
print(np.min(arr43))

2


In [212]:
print(np.max(arr43, axis=0))
#prints the max value in each column

[8 9]


In [230]:
arr1 = np.arange(2,10).reshape(4,2)
print(arr1)

[[2 3]
 [4 5]
 [6 7]
 [8 9]]


In [231]:
print(np.min(arr1,axis=1))
#print(التغيير على مستوى الصف,اسم المصفوفة,العملية الاحصائية,اختصار اسم المكتبة.min(arr1,axis=1))

[2 4 6 8]


In [232]:
print(np.max(arr1,axis=0))

[8 9]


In [234]:
print(np.sum(arr1, axis=1))

[ 5  9 13 17]


## الترتيب ابجدي للنصوص وترتيب من الاصغر الى الاكبرللارقام

In [319]:
b = np.array(['omar','ahmad','khlad'])
np.sort(b)

array(['ahmad', 'khlad', 'omar'], dtype='<U5')

In [320]:
l = np.array([5,4,3])
np.sort(l)

array([3, 4, 5])

## sort by index

In [238]:
#اظهار ترتيب العناصر من خلال موقع العنصر
arr2 = np.array([1, -30, 10, 15, 3])
out_arr = np.argsort(arr2)
print(out_arr)
print(arr2)

[1 0 4 2 3]
[  1 -30  10  15   3]


In [239]:
res = np.argsort(arr2)[::-1]
print(res)
#reversed by index

[3 2 4 0 1]


In [240]:
arr3 = np.arange(6).reshape(2,3) + 10
print(arr3)
#لزيادة مقدار معين ثابت للنطاق من الارقام


[[10 11 12]
 [13 14 15]]


In [245]:
print(arr2.argmax())
print(arr2.argmin())
#مكان اعلى قيم واقل قيمة ك اندسك

3
1


## #Numpy - Broadcasting 


In [246]:
a = np.array([75,80,73,85])
b = np.array([7])
#b = np.array([7,7,7,7]) اذ كانت القيمة واحده المراد جمعها على المصفوفة الاولى مو لازم تكرر الرقم 


In [247]:
print(a+b)

[82 87 80 92]


In [248]:
print(a-b)

[68 73 66 78]


In [250]:
print(a*b)

[525 560 511 595]


In [60]:
f = np.array([1,2,3,4,5,6,7,8,9])

In [65]:
g = np.expand_dims(f,axis=1)
#g = np.expand_dims(f,axis=1 ثلاث اسطر وعمود واحد على حسب عدد القيم المعطاه يرجح الكف يم الاسطر)
#g = np.expand_dims(f,axis=0 ثلاث اعمدة وسطر واحد على حسب عدد القيم المعطاه مره يرجح الكف للاعمدة )

g


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [66]:
print(g.shape)

(9, 1)


## لتقسيم المصفوفات


In [267]:
np.split(f,3)
#np.split(f,نقسم المصفوفة الرئيسية على كم مصفوفة فرعية)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [77]:
f = np.array([1,2,3,4,5,6,7,8,9,10])
a, b ,v= np.split(f, [5,2])
print(a)
print(b)
print(v)


[1 2 3 4 5]
[]
[ 3  4  5  6  7  8  9 10]


In [80]:
 b = np.array([1,2,3,4,5,6,7,8,9])
new = np.array_split(b,4)
print(new[0])
print(new[1])
print(new[2])
print(new[3])

[1 2 3]
[4 5]
[6 7]
[8 9]


## نسخ قيم مصفوفة الى اخر

In [81]:
np.random.seed(0)
h = np.random.randint(1,20,size=(3,2))
h

array([[13, 16],
       [ 1,  4],
       [ 4,  8]])

In [297]:
hc = np.copy(h)+5
hc

array([[18, 21],
       [ 6,  9],
       [ 9, 13]])

In [299]:
j = np.array([1,2,4,6,7,8])
any_max_than5 = np.where(j>5)
any_max_than5
#يطلع لك القيم ك as index

(array([3, 4, 5], dtype=int64),)

In [300]:
print(j[any_max_than5])

[6 7 8]


In [301]:
print(j>5)

[False False False  True  True  True]


In [302]:
n = j >5 
print(n)

[False False False  True  True  True]


In [303]:
#([1,2,4,6,7,8])
n = j %2==0 
print(n)

[False  True  True  True False  True]


In [304]:
print(np.full((2,3,3),"m555ar",dtype="str"))
#لسى ماني قادر املا مصفوفة باسم معين بدال حرف

[[['m' 'm' 'm']
  ['m' 'm' 'm']
  ['m' 'm' 'm']]

 [['m' 'm' 'm']
  ['m' 'm' 'm']
  ['m' 'm' 'm']]]


In [309]:
s = np.array([1,2])
np.full(s.shape,"عمرابراهيم الميلبى")

array(['عمرابراهيم الميلبى', 'عمرابراهيم الميلبى'], dtype='<U18')

In [305]:
np.full_like(j,5)
#np.full_like(,حدد الرقم المراد ملء به المصفوفة ضع اسم المصفوفة المراد تقليدها)

array([5, 5, 5, 5, 5, 5])

In [84]:
k = ['the second year in DS']
p = ['   and its the end of this pragram']
print(np.char.add(k,p))
#المسافة تحسب في بداية المصفوفة الثانية سوف تلصق بنهاية المصفوفة الاولى

['the second year in DS   and its the end of this pragram']


In [85]:
q = 'he is a good boy'
print(np.char.replace(q,'is','was'))

he was a good boy


In [96]:
from numpy import random
x = np.array([1,2,3,4,5])
random.shuffle(x)
x

array([1, 2, 5, 3, 4])

array([1, 2, 3])